name: GitHub Actions CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Stage 1 - Checkout code
        uses: actions/checkout@v4

      - name: Stage 2 - Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Stage 3 - Maven build
        run: mvn clean compile

      - name: Stage 4 - Unit tests
        run: mvn test

      - name: Stage 5 - Create JAR
        run: mvn package -DskipTests

      - name: Stage 6 - Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: target/*.jar

      - name: Stage 7 - Build Docker image
        run: docker build --tag java-github-actions-poc:latest .

      - name: Stage 8 - Verify Docker image
        run: docker image inspect java-github-actions-poc:latest